version: '3.1'

services:

  mysqlserver2:
    image: mysql:latest
    container_name: mysqlserver2
    ports:
       - "3306:3306" 
    environment:
       MYSQL_ROOT_PASSWORD: 'root'
       MYSQL_DATABASE: 'city-db' 
       
  tomcat-db-api:
    image: spring_demo
    container_name: springdemoapp2
    build:
       context: .
       dockerfile: Dockerfile
    ports:
       - "8080:8080"
    depends_on:
       - mysqlserver2
    
